version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/travel_db

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db

